### ISSUE TITLE
Support github enterprise

### ISSUE THREAD

**Issue by yeonseok-seo** [rdohms/com.dms.streamdeck.github#3]
Hi, thanks for the plugin.

Can you add support for github enterprise?

I wish I can do it by myself and make a pull request, 
but it couldn't figure out how to build and test your project

**Comment by rdohms** [comment]
Thanks for the feedback!

I'll add a separate ticket with "how to run this for dev" also.

When you say enterprise, you mean the on-prem version, right? So the basic need would be to adjust the API URL to the on-prem one?

**Comment by yeonseok-seo** [comment]
Yeap

Radio button and textbox for base URL would work.

Thanks!

**Comment by rdohms** [comment]
Alright, I just sent the update to Elgato, it should be available within the next day.
